### Temas cronograma

GET https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/
Accept: application/json

###

### USAR ESTE METODO PARA CREAR UN TEMA CRONOGRAMA
POST https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/create/
Content-Type: application/json
Accept: application/json

{
    "cronograma": 1,
    "descripcion": "Tema de prueba",
    "tiempo_en_semanas": 1,
    "completado": false
}

###

GET https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/2
Accept: application/json

###

PUT https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/2/
Content-Type: application/json
Accept: application/json

{
    "cronograma": 1,
    "descripcion": "Tema Actualizado",
    "orden": 2,
    "tiempo_en_semanas": 2,
    "completado": false
}

###

DELETE https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/13/
Accept: application/json

###

PUT https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/2/check/
Content-Type: application/json
Accept: application/json

{
    "fecha_actual": "2024-08-15"
}

###
