# Métodos HTTP
# Endpoints usados para Feature 1
# Creado por Christian Hernández

# Obtener lista de estudiantes en riesgo de abandono
GET https://syncademic-0-1.onrender.com/syncademic/asistencia/estudiantes-en-riesgo/1/
Accept: application/json

###
# Obtener lista de estudiantes
GET https://syncademic-0-1.onrender.com/syncademic/asistencia/lista-estudiantes/
Accept: application/json
