# Métodos HTTP
# Endpoints usados para Feature 2
# Creado por Alejandra Colcha

# Obtener lista de estudiantes con sus promedios
GET https://syncademic-0-1.onrender.com/syncademic/control-notas/estudiantes/1/6/1//
Accept: application/json

###
# Obtener lista de estudiantes para iniciar registro de una nota
GET https://syncademic-0-1.onrender.com/syncademic/control-notas/1/6/1//
Accept: application/json

###
# Guardar notas de estudiantes y obtener el recuento de alertas
POST https://syncademic-0-1.onrender.com/syncademic/control-notas/1/6/1//
content-type: application/json

[
  {
    "id_estudiante": 1,
    "nombre": "Juan Perez",
    "nota": 10,
    "tema": "introduccion",
    "tipo_actividad": 1
  },
  {
    "id_estudiante": 3,
    "nombre": "Carlos Martinez",
        "nota": 6.5,
    "tema": "introduccion",
    "tipo_actividad": 1
  },
  {
    "id_estudiante": 5,
    "nombre": "Luis Sanchez",
        "nota": 9.5,
    "tema": "introduccion",
    "tipo_actividad": 1
  },
  {
    "id_estudiante": 9,
    "nombre": "Pedro Torres",
        "nota": 10,
    "tema": "introduccion",
    "tipo_actividad": 1
  },
  {
    "id_estudiante": 11,
    "nombre": "Andres Suarez",
        "nota": 8,
    "tema": "introduccion",
    "tipo_actividad": 1
  }
]

