###
GET http://127.0.0.1:8000/F7/api/evaluacion-docente/docentes-por-promedio/4/1/
    Accept: application/json

###
GET http://127.0.0.1:8000/F7/api/evaluacion-docente/sugerencias-docentes/
    Accept: application/json
