### Temas cronograma

GET http://127.0.0.1:8000/syncademic/tema-cronograma/
Accept: application/json

###

GET https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/16
Accept: application/json

###

PUT http://127.0.0.1:8000/syncademic/tema-cronograma/53/
Content-Type: application/json
Accept: application/json

{
    "cronograma": 20,
    "descripcion": "Tema Actualizado",
    "orden": 3,
    "tiempo_en_semanas": 2,
    "completado": false
}

###

DELETE https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/13/
Accept: application/json

###

PUT http://127.0.0.1:8000/syncademic/tema-cronograma/53/check/
Content-Type: application/json
Accept: application/json

{
    "fecha_actual": "2024-08-15"
}

###

### USAR ESTE METODO PARA CREAR UN TEMA CRONOGRAMA
POST https://syncademic-0-1.onrender.com/syncademic/tema-cronograma/create/
Content-Type: application/json
Accept: application/json

{
    "cronograma": 14,
    "descripcion": "Tema de prueba",
    "tiempo_en_semanas": 1,
    "completado": false
}
