# Métodos HTTP
# Endpoints usados para Feature 8

###
# Obtener lista de capacitaciones de un profesor SI
GET http://0.0.0.0:8000/syncademic/capacitacion/6/capacitaciones
Accept: application/json

###
# Obtener una lista de docentes con su puntuacion actual
GET http://0.0.0.0:8000/syncademic/capacitacion/docentes
Accept: application/json

###
# Obtener docente
GET http://0.0.0.0:8000/syncademic/capacitacion/docente/6

###
# Obtener una lista de docentes con sus puntuaciones viejas y perido
GET http://0.0.0.0:8000/syncademic/capacitacion/6/puntuacionesViejas
Accept: application/json

###
# Crear nueva capacitacion
POST http://0.0.0.0:8000/syncademic/capacitacion/nueva/
content-type: application/json

[
  {
    "docente": 1,
    "nombre_capacitacion": "Curso de Matemáticas",
    "area": "Matemáticas",
    "periodo": 6
}
]