# Generated by Django 5.0.7 on 2024-08-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_tipo_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('total_clases', models.IntegerField()),
                ('total_inscritos', models.IntegerField()),
                ('total_comprende', models.IntegerField()),
                ('prerequisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anteriores', to='syncademic.asignatura')),
                ('subsecuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='syncademic.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id_cronograma', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='syncademic.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_incidencias', models.IntegerField()),
                ('grupo_actual', models.IntegerField(default=1)),
                ('prioridad', models.CharField(default='BAJA', max_length=5)),
                ('asignaturas', models.ManyToManyField(related_name='asignaturas', to='syncademic.asignatura')),
                ('periodo_cursando', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='syncademic.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.IntegerField(choices=[(1, 'Heteroevaluacion'), (2, 'Autoevaluacion'), (3, 'Coevaluacion'), (4, 'Total')])),
                ('calificacion', models.FloatField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.docente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialNotas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.IntegerField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tema', models.TextField()),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.asignatura')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='syncademic.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.periodo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.tipoactividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField()),
                ('dia', models.CharField(max_length=10)),
                ('presente', models.BooleanField(default=False)),
                ('asignatura',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.asignatura')),
                ('estudiante',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'semana', 'dia')},
            },
        ),
    ]
