# Generated by Django 5.0.7 on 2024-08-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='estado',
            field=models.CharField(default='n/a', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='TemaCronograma',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('tiempo_en_semanas', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('semana_finalizacion_relativa_a_inicio', models.IntegerField(null=True)),
                ('fecha_completado', models.DateField(null=True)),
                ('id_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='syncademic.cronograma')),
            ],
        ),
    ]
