# Generated by Django 5.0.6 on 2024-08-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('subaspectos', models.JSONField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='BAJO', max_length=20)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.JSONField(default=dict)),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncademic.aspecto')),
            ],
        ),
    ]
