# Generated by Django 5.0.7 on 2024-08-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0002_cronograma_estado_cronograma_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='id_asignatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='syncademic.asignatura'),
        ),
    ]
