# Generated by Django 5.0.7 on 2024-08-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0003_alter_cronograma_id_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='id_asignatura',
            new_name='asignatura',
        ),
    ]
