# Generated by Django 5.0.7 on 2024-08-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0004_rename_id_asignatura_cronograma_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temacronograma',
            old_name='id_cronograma',
            new_name='cronograma',
        ),
    ]
