# Generated by Django 5.0.7 on 2024-08-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0005_rename_id_cronograma_temacronograma_cronograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='id_cronograma',
            new_name='cronograma',
        ),
    ]
