# Generated by Django 5.0.7 on 2024-08-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncademic', '0006_rename_id_cronograma_cronograma_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='asignatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='syncademic.asignatura'),
        ),
    ]
