from syncademic.services.notas_service import NotasService
from syncademic.services.evaluacion_docente_service import *
from syncademic.services.seguimiento_malla_service import SeguimientoService


from syncademic.services.asistencia_service import AsistenciaService

from syncademic.services.asistencia_service import AsistenciaService
from syncademic.services.cronograma_service import CronogramaService
from syncademic.services.tema_cronograma_service import TemaCronogramaService


