from syncademic.services.notas_service import NotasService
from syncademic.services.evaluacion_docente_service import *
from syncademic.services.seguimiento_malla_service import SeguimientoService
from syncademic.services.asistencia_service import AsistenciaService
