from .notas_serializer import NotasSerializer
from .estudiante_serializer import EstudianteSerializer, ListaEstudianteSerializer
from .asistencia_serializer import AsistenciaSerializer
from .asignatura_serializer import AsignaturaSerializer
